blank_issues_enabled: false
name: GitHub Issue Template Configuration
description: Configure the issue templates for your repository.
contact_links:
  - name: GitHub Community Support
    url: https://github.com/orgs/community/discussions
    about: Please ask and answer questions here.
  - name: GitHub Security Bug Bounty
    url: https://bounty.github.com/
    about: Please report security vulnerabilities here.
  - name: GitHub Issue Templates
    url: ./ISSUE_TEMPLATE/1-feature-request.yml
    about: Please use the issue templates provided in this repository.