name: 📌 Feature Task
description: Issue for a new feature, configuration, or component
title: '📌 [Type] <Issue Title>'
labels: ['type:setup', 'type:component', 'effort:2']
body:
  - type: select
    id: effort
    options:
      - label: 1: Low
        value: 1
      - label: 2: Medium
        value: 2
      - label: 3: High
        value: 3
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe clearly what this task is about and the expected outcome.
      placeholder: Describe the purpose and scope of this issue
    validations:
      required: true

  - type: textarea
    id: subtasks
    attributes:
      label: Subtasks
      description: Add checkboxes for subtasks to complete
      value: |
        - [ ] Setup initial structure
        - [ ] Write implementation
        - [ ] Add tests (if needed)
        - [ ] Document usage (Storybook or MDX)
      render: markdown

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Define what conditions must be met to close this issue.
      placeholder: |
        - [ ] The component renders as expected
        - [ ] Linting and formatting pass
        - [ ] Visual consistency verified
